name: Dragon ASCII Workflow

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Run dragon script
        run: ./script.sh

      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

  download:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download dragon artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
          path: ./artifact

      - name: Show downloaded file
        run: cat ./artifact/dragon.txt
